export const RESTAURANT_FETCH_LOADING = 'RESTAURANT_FETCH_LOADING';
export const RESTAURANT_FETCH_SUCCEED = 'RESTAURANT_FETCH_SUCCEED';
export const RESTAURANT_FETCH_ERROR = 'RESTAURANT_FETCH_ERROR';
